/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Conexion.Conexion;

/**
 *
 * @author Enzo
 */
public class VentanaVademecum extends javax.swing.JFrame {
	DefaultTableModel model;
    /**
     * Creates new form VentanaVademecum2
     */
    public VentanaVademecum() {
        initComponents();
        setSize(918, 529);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Vademecum");
        cargar("");
    }
    private void cargar(String valor){
    	String [] titulos= {"Nombre", "Posología", "Indicaciones"};
    	String [] registros= new String[3];
    	String sql= "SELECT * FROM vademecum WHERE vad_cod LIKE '%"+valor+"%' ORDER BY vad_cod ASC";
    	model= new DefaultTableModel (null, titulos);
    	Conexion cc= new Conexion();
    	Connection cn= cc.conexion();
    	try {
    		Statement st= cn.createStatement();
    		ResultSet rs= st.executeQuery(sql);
    		while(rs.next()){
    			registros[0]=rs.getString("vad_nom");
    			registros[1]=rs.getString("vad_poso");
    			registros[2]=rs.getString("vad_ind");
    			model.addRow(registros);
    		}
    		tablaVade.setModel(model);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null,"Error: "+e , "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
		}
    }
    private void guardar(){
    	Conexion cc= new Conexion();
    	Connection cn= cc.conexion();
    	String sql="INSERT INTO vademecum (vad_nom, vad_poso, vad_ind) VALUES (?,?,?)";
    	String nom= campoNom.getText();
    	String poso= comboPoso.getSelectedItem().toString();
    	String indi= areaIndi.getText();    
    	try {
    		PreparedStatement psd= cn.prepareStatement(sql);
    		psd.setString(1, nom);
    		psd.setString(2, poso);
    		psd.setString(3, indi);
    		int n= psd.executeUpdate();
    		if(n>0){
    			JOptionPane.showMessageDialog(null,"Se han guardado los datos");    			
    		}    		
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null,"Error :" +e, "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
		}
    }
    private void eliminar (){
    	Conexion cc= new Conexion();
    	Connection cn= cc.conexion();
    	//String 
    }
    private void modificar(){}
    private void limpiar(){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPoso = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelIndi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaIndi = new javax.swing.JTextArea();
        comboPoso = new javax.swing.JComboBox<>();
        campoNom = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelBuscar = new javax.swing.JLabel();
        campoBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVade = new javax.swing.JTable(){
        	private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {                
                    return false;               
            };
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        labelPoso.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        labelPoso.setText("Posologia");
        jPanel1.add(labelPoso);
        labelPoso.setBounds(20, 80, 90, 21);

        labelNom.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        labelNom.setText("Nombre");
        jPanel1.add(labelNom);
        labelNom.setBounds(20, 20, 70, 21);

        labelIndi.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        labelIndi.setText("Indicaciones");
        jPanel1.add(labelIndi);
        labelIndi.setBounds(20, 140, 100, 21);

        areaIndi.setColumns(20);
        areaIndi.setRows(5);
        jScrollPane1.setViewportView(areaIndi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 300, 180);

        comboPoso.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        comboPoso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 vez al dia", "2 veces al dia", "3 veces al dia", "cada 24 hs", "1 vez por semana" }));
        jPanel1.add(comboPoso);
        comboPoso.setBounds(130, 80, 140, 30);

        campoNom.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel1.add(campoNom);
        campoNom.setBounds(130, 20, 140, 30);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(210, 370, 90, 40);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt){
        		btn_guardarActionPerformed(evt);
        	}
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(10, 370, 90, 40);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar);
        btnModificar.setBounds(110, 370, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 330, 480);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        labelBuscar.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        labelBuscar.setText("Buscar");
        jPanel2.add(labelBuscar);
        labelBuscar.setBounds(10, 10, 70, 30);
        jPanel2.add(campoBuscar);
        campoBuscar.setBounds(100, 10, 180, 30);

        tablaVade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaVade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaVade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaVade);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 530, 410);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 10, 550, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    protected void btn_guardarActionPerformed(ActionEvent evt){
    	guardar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVademecum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVademecum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVademecum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVademecum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVademecum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaIndi;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JTextField campoNom;
    private javax.swing.JComboBox<String> comboPoso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelIndi;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPoso;
    private javax.swing.JTable tablaVade;
    // End of variables declaration//GEN-END:variables
}
