/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Enzo
 */
public class VentanaTurnos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTurnos2
     */
    public VentanaTurnos() {
        initComponents();
        setSize(1005,500);
        setLocationRelativeTo(null); 
        setResizable(false);
        setTitle("Turnos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoCel = new javax.swing.JTextField();
        campoNom = new javax.swing.JTextField();
        campoDire = new javax.swing.JTextField();
        campoTel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jsfMin = new com.toedter.components.JSpinField();
        jsfHora = new com.toedter.components.JSpinField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTurnos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        campoBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Celular");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 20, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hora");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 150, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 210, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Direccion");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 270, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tel/Cel");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 330, 60, 30);

        campoCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(campoCel);
        campoCel.setBounds(110, 20, 130, 30);

        campoNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(campoNom);
        campoNom.setBounds(110, 210, 130, 30);

        campoDire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(campoDire);
        campoDire.setBounds(110, 270, 130, 30);

        campoTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(campoTel);
        campoTel.setBounds(110, 330, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 80, 50, 30);

        jdcFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(jdcFecha);
        jdcFecha.setBounds(110, 80, 130, 30);
        jPanel3.add(jsfMin);
        jsfMin.setBounds(210, 150, 50, 30);
        jPanel3.add(jsfHora);
        jsfHora.setBounds(110, 150, 50, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Hs");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(170, 150, 30, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Mins");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(270, 150, 30, 30);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        jPanel3.add(btnGuardar);
        btnGuardar.setBounds(13, 420, 90, 40);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        jPanel3.add(btnModificar);
        btnModificar.setBounds(130, 420, 90, 40);

        btnBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        jPanel3.add(btnBorrar);
        btnBorrar.setBounds(240, 420, 90, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 370, 480);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        tablaTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaTurnos);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 600, 400);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Buscar");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 10, 50, 30);

        campoBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(campoBuscar);
        campoBuscar.setBounds(100, 10, 160, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(380, 0, 620, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTurnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JTextField campoCel;
    private javax.swing.JTextField campoDire;
    private javax.swing.JTextField campoNom;
    private javax.swing.JTextField campoTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private com.toedter.components.JSpinField jsfHora;
    private com.toedter.components.JSpinField jsfMin;
    private javax.swing.JTable tablaTurnos;
    // End of variables declaration//GEN-END:variables
}
